name: Build Documentation

# Controls when the action will run.
on:
  # run on push, manual dispatch and on a schedule
  workflow_dispatch:
  workflow_call:
  release:
    types: [ released ]


jobs:
  build_docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ hashFiles('requirements/*/*.txt') }}
          restore-keys: |
            pip-cache

      - name: Install python requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements-dev.txt

      - name: Create cache directory
        run: |
          mkdir doc_cache  # make sure cache dir exists

      - name: Cache FastF1
        uses: actions/cache@v2
        with:
          path: ./doc_cache
          key: fastf1-${{ secrets.CACHE_VERSION }}-doc-cache-${{ hashFiles('*.*') }}
          restore-keys: |
            fastf1-${{ secrets.CACHE_VERSION }}-doc-cache

      - name: Install Fast-F1 from sources
        run: |
          python3 -m pip install -e .

      - name: Checkout current docs
        run: |
          mkdir -p docs/build/_html
          cd docs/build/_html
          git init
          git remote add origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull origin gh-pages

      - name: Build docs
        run: |
          mkdir test_cache  # not really need but pytest setup relies on it 
          python setup.py build_sphinx -a -E

      - name: Publish docs
        if: github.event_name == 'release'
        run: |
          cd docs/build/_html
          git add .
          git commit -m "$GITHUB_REF_NAME ($GITHUB_JOB) ci release"
          git push origin gh-pages --force

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v3
        if: github.event_name != 'release'
        with:
          name: "doc-build-$GITHUB_REF_NAME-$GITHUB_JOB"
          path: docs/build/_html