name: Publish Documentatio

on:
  workflow_dispatch:

jobs:
  publish-docs:
    name: Build and Publish Docs
    uses: ./.github/workflows/docs.yml
    with:
      publish: true
    secrets:
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}